### ISSUE TITLE
CocoaPods support

### ISSUE THREAD

**Issue by ky1vstar** [fwcd/swift-qrcode-generator#2]
Hi! I really appreciate you work and library you've provided. You might ask: why do you want CocoaPods support when there is built-in support for QR code generation on iOS. But it is only partly true. Thing is `CIQRCodeGenerator` generates bitmap. My current task is to put QR code to PDF and bitmap generated by builtin tool looks crappy. I know that I can use your library directly via SPM, but the only dependency manager we are using in our project is CocoaPods, so I don't want to use SPM just for one dependency. I can create a PR with CocoaPods integration and appropriate CI. What do you think?

**Comment by fwcd** [comment]
Sounds good!

**Comment by ky1vstar** [comment]
I'm really grateful for the quick answer! So I'll provide a PR soon

**Comment by ky1vstar** [comment]
@fwcd do you prefer to release CocoaPods versions manually or I should create Workflow for automatic release?

**Comment by fwcd** [comment]
A workflow that automatically does that whenever a tag is pushed would be great.

**Comment by ky1vstar** [comment]
@fwcd Hi! Sorry, but is there any chance you can review the pull request till the end of this week?

**Comment by fwcd** [comment]
Should be live on CocoaPods now

**Comment by ky1vstar** [comment]
Thanks a lot! I suppose that at least lib linting should exist in darwin CI
