### ISSUE TITLE
[Cocoapods] Xcode 14.3 generates an error when adding SwiftQRCodeGenerator as a dependency for macOS

### ISSUE THREAD

**Issue by dagronf** [fwcd/swift-qrcode-generator#5]
Hi there!

I've noticed an unusual issue when trying to add SwiftQRCodeGenerator as a dependency in my podspec file

```
s.dependency                 'SwiftQRCodeGenerator'
```

It would appear that Xcode 14.3 has recently dropped some arc-related frameworks, which affects the minimum deployment versions that can be built with Xcode 14.3, which in turn causes `pod spec lint` to fail on any podspec that depends on SwiftQRCodeGenerator. If I go back to Xcode 14.2 the issue goes away - so it's definitely been introduced in a later 14.3 release. It appears that the issue only affects the mac build as far as I can tell.

```
    ld: file not found: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_macosx.a
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I _think_ this is relating to the 10.10 deployment target. I was wondering whether it would be possible to up the os version in the podspec file to fix this issue for Xcode 14.3?

```
s.osx.deployment_target     = '10.13'
```

Existing users who still need support for 10.10 can still link against 1.0.4, so there'd be a backwards compatibility path.

Refs: -

https://github.com/CocoaPods/CocoaPods/issues/11839

and

https://developer.apple.com/forums/thread/725300

Many thanks for a great library!

**Comment by fwcd** [comment]
Is this fixed by #6?

**Comment by dagronf** [comment]
That's great mate.  If we could tag that latest release with a v2.0.0 that would allow Cocoapods to pull the updated version when requested.

**Comment by fwcd** [comment]
Done

**Comment by dagronf** [comment]
Brilliant mate.  I'm just waiting for the CI to complete which should automatically push the v2.0.0 branch to Cocoapods and then I will test and let you know.

**Comment by fwcd** [comment]
Looks like we'll have to bump the deployment targets further to build with recent versions of Xcode: https://github.com/fwcd/swift-qrcode-generator/actions/runs/6924089904/job/18832847281

**Comment by dagronf** [comment]
The [deploy action](https://github.com/fwcd/swift-qrcode-generator/actions/runs/6924089904) has failed.  Seems to be something relating to the authentication when pushing up to Cocoapods.

Have you got some time to check?

**Comment by fwcd** [comment]
2.0.1 is now deployed

**Comment by dagronf** [comment]
Ah I'm so sorry to be a pain - but you've updated the podspec to use 2.0.2, but you've only tagged the repo with 2.0.1

Any chance of adding the 2.0.2 tag?

**Comment by fwcd** [comment]
2.0.2 is tagged and pushed (which should fix the validation check for the iOS target too). 2.0.3 on the main branch is the unreleased development version - I tend to bump version numbers immediately after releasing. I admittedly haven't worked a lot with CocoaPods yet, so if that poses an issue for consuming the pod, let me know.

**Comment by dagronf** [comment]
Hey @fwcd all looks great.  After jumping through some hoops with my [own project](https://github.com/dagronf/QRCode) to get cocoapods updated it all seems to be up and running.

Thank you so much!
